// Copyright 2022 Romain Edelmann
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


const translations = {
  en: {
    "add": "Add",
    "cancel": "Cancel",
    "apply": "Apply",
    "save": "Save",
    "exit": "Exit",
    "reset": "Reset",
    "choose_replacements": "Select replacements",
    "new-goal": "New goal",
    "about": "About",
    "help": "Help",
    "undo": "Undo",
    "redo": "Redo",
    "settings": "Settings",
    "load": "Load",
    "about_text": "Bernays is a visual proof assistant for propositional logic based on natural deduction.",
    "about_credits": "Bernays was created by Romain Edelmann.",
    "about_license": "This work is licensed under the Apache License 2.0.",
    "about_source": "Source code is available on GitHub.",
    "close": "Close",
  },
  fr: {
    "add": "Ajouter",
    "cancel": "Annuler",
    "apply": "Appliquer",
    "save": "Sauvegarder",
    "exit": "Quitter",
    "reset": "Réinitialiser",
    "choose_replacements": "Sélectionner les remplacements",
    "new-goal": "Nouveau but",
    "about": "À propos",
    "help": "Aide",
    "undo": "Annuler",
    "redo": "Rétablir",
    "settings": "Paramètres",
    "load": "Charger",
    "about_text": "Bernays est un assistant de preuve visuel pour la logique propositionnelle basé sur la déduction naturelle.",
    "about_credits": "Bernays a été créé par Romain Edelmann.",
    "about_license": "Ce travail est sous licence Apache 2.0.",
    "about_source": "Le code source est disponible sur GitHub.",
    "close": "Fermer",
  },
  de: {
    "add": "Hinzufügen",
    "cancel": "Abbrechen",
    "apply": "Anwenden",
    "save": "Speichern",
    "exit": "Beenden",
    "reset": "Zurücksetzen",
    "choose_replacements": "Wählen Sie Ersatzvariablen",
    "new-goal": "Neues Ziel",
    "about": "Über",
    "help": "Hilfe",
    "undo": "Rückgängig",
    "redo": "Wiederholen",
    "settings": "Einstellungen",
    "load": "Laden",
    "about_text": "Bernays ist ein visueller Beweisassistent für die Aussagenlogik, der auf natürlicher Deduktion basiert.",
    "about_credits": "Bernays wurde von Romain Edelmann entwickelt.",
    "about_license": "Dieses Werk ist unter der Apache-Lizenz 2.0 veröffentlicht.",
    "about_source": "Quellcode ist auf GitHub verfügbar.",
    "close": "Schließen",
  },
  es: {
    "add": "Añadir",
    "cancel": "Cancelar",
    "apply": "Aplicar",
    "save": "Guardar",
    "exit": "Salir",
    "reset": "Reiniciar",
    "choose_replacements": "Seleccione sustituciones",
    "new-goal": "Nuevo objetivo",
    "about": "Acerca de",
    "help": "Ayuda",
    "undo": "Deshacer",
    "redo": "Rehacer",
    "settings": "Configuración",
    "load": "Cargar",
    "about_text": "Bernays es un asistente de prueba para la lógica proposicional basado en la deducción natural.",
    "about_credits": "Bernays fue creado por Romain Edelmann.",
    "about_license": "Este trabajo está licenciado bajo la licencia Apache 2.0.",
    "about_source": "El código fuente está disponible en GitHub.",
    "close": "Cerrar",
  },
  it: {
    "add": "Aggiungi",
    "cancel": "Annulla",
    "apply": "Applica",
    "save": "Salva",
    "exit": "Esci",
    "reset": "Reimposta",
    "choose_replacements": "Scegli sostituzioni",
    "new-goal": "Nuovo obiettivo",
    "about": "Informazioni",
    "help": "Aiuto",
    "undo": "Annulla",
    "redo": "Ripeti",
    "settings": "Impostazioni",
    "load": "Carica",
    "about_text": "Bernays è un asistente di prova per la logica proposicionale basato sulla deduzione naturale.",
    "about_credits": "Bernays è stato creato da Romain Edelmann.",
    "about_license": "Questo lavoro è sotto licenza Apache 2.0.",
    "about_source": "Il codice sorgente è disponibile su GitHub.",
    "close": "Chiudi",
  },
  ja: {
    "add": "追加",
    "cancel": "キャンセル",
    "apply": "適用",
    "save": "保存",
    "exit": "終了",
    "reset": "リセット",
    "choose_replacements": "置換を選択",
    "new-goal": "新しい目標",
    "about": "約",
    "help": "助けて",
    "undo": "やり直し",
    "redo": "やり直し",
    "settings": "設定",
    "load": "ロード",
    "about_text": "Bernaysは、自然演繹に基づく命題論理のための視覚的な証明アシスタントです。",
    "about_credits": "Bernaysは、Romain Edelmannによって作成されました。",
    "about_license": "この作品は、Apacheライセンス2.0下で提供されています。",
    "about_source": "ソースコードはGitHubで利用できます。",
    "close": "閉じる",
  },
  nl: {
    "add": "Toevoegen",
    "cancel": "Annuleren",
    "apply": "Toepassen",
    "save": "Opslaan",
    "exit": "Afsluiten",
    "reset": "Reset",
    "choose_replacements": "Kies vervangingen",
    "new-goal": "Nieuw doel",
    "about": "Over",
    "help": "Help",
    "undo": "Ongedaan maken",
    "redo": "Opnieuw",
    "settings": "Instellingen",
    "load": "Laden",
    "about_text": "Bernays is een visuele bewijsassistent voor de logica propositiele, die op natuurlijke deduksie gebaseerd is.",
    "about_credits": "Bernays is ontwikkeld door Romain Edelmann.",
    "about_license": "Dit werk is onder de Apache-licentie 2.0.",
    "about_source": "De broncode is beschikbaar op GitHub.",
    "close": "Sluiten",
  },
  pt: {
    "add": "Adicionar",
    "cancel": "Cancelar",
    "apply": "Aplicar",
    "save": "Salvar",
    "exit": "Sair",
    "reset": "Resetar",
    "choose_replacements": "Escolha substituições",
    "new-goal": "Novo objetivo",
    "about": "Sobre",
    "help": "Ajuda",
    "undo": "Desfazer",
    "redo": "Refazer",
    "settings": "Configurações",
    "load": "Carregar",
    "about_text": "Bernays é um assistente de prova para a lógica proposicional baseado na dedução natural.",
    "about_credits": "Bernays foi desenvolvido por Romain Edelmann.",
    "about_license": "Este trabalho está licenciado sob a licença Apache 2.0.",
    "about_source": "O código-fonte está disponível no GitHub.",
    "close": "Fechar",
  },
};

export function _(key, lang) {
  var selected_lang = lang || window.navigator.userLanguage || window.navigator.language || "en";
  const lang_only = selected_lang.split("-")[0];
  if (lang_only in translations) {
    if (key in translations[lang_only]) {
      return translations[lang_only][key];
    }
  }
  if (key in translations["en"]) {
    return translations["en"][key];
  }
  return key;
}