
const translations = {
  en: {
    "add": "Add",
    "cancel": "Cancel",
    "apply": "Apply",
    "save": "Save",
    "exit": "Exit",
    "reset": "Reset",
    "choose_replacements": "Select replacements",
    "new-goal": "New goal",
    "about": "About",
    "help": "Help",
    "undo": "Undo",
    "redo": "Redo",
    "settings": "Settings",
    "load": "Load",
  },
  fr: {
    "add": "Ajouter",
    "cancel": "Annuler",
    "apply": "Appliquer",
    "save": "Sauvegarder",
    "exit": "Quitter",
    "reset": "Réinitialiser",
    "choose_replacements": "Sélectionner les remplacements",
    "new-goal": "Nouveau but",
    "about": "À propos",
    "help": "Aide",
    "undo": "Annuler",
    "redo": "Rétablir",
    "settings": "Paramètres",
    "load": "Charger",
  },
  de: {
    "add": "Hinzufügen",
    "cancel": "Abbrechen",
    "apply": "Anwenden",
    "save": "Speichern",
    "exit": "Beenden",
    "reset": "Zurücksetzen",
    "choose_replacements": "Wählen Sie Ersatzvariablen",
    "new-goal": "Neues Ziel",
    "about": "Über",
    "help": "Hilfe",
    "undo": "Rückgängig",
    "redo": "Wiederholen",
    "settings": "Einstellungen",
    "load": "Laden",
  },
  es: {
    "add": "Añadir",
    "cancel": "Cancelar",
    "apply": "Aplicar",
    "save": "Guardar",
    "exit": "Salir",
    "reset": "Reiniciar",
    "choose_replacements": "Seleccione sustituciones",
    "new-goal": "Nuevo objetivo",
    "about": "Acerca de",
    "help": "Ayuda",
    "undo": "Deshacer",
    "redo": "Rehacer",
    "settings": "Configuración",
    "load": "Cargar",
  },
  it: {
    "add": "Aggiungi",
    "cancel": "Annulla",
    "apply": "Applica",
    "save": "Salva",
    "exit": "Esci",
    "reset": "Reimposta",
    "choose_replacements": "Scegli sostituzioni",
    "new-goal": "Nuovo obiettivo",
    "about": "Informazioni",
    "help": "Aiuto",
    "undo": "Annulla",
    "redo": "Ripeti",
    "settings": "Impostazioni",
    "load": "Carica",
  },
  ja: {
    "add": "追加",
    "cancel": "キャンセル",
    "apply": "適用",
    "save": "保存",
    "exit": "終了",
    "reset": "リセット",
    "choose_replacements": "置換を選択",
    "new-goal": "新しい目標",
    "about": "約",
    "help": "助けて",
    "undo": "やり直し",
    "redo": "やり直し",
    "settings": "設定",
    "load": "ロード",
  },
  ko: {
    "add": "추가",
    "cancel": "취소",
    "apply": "적용",
    "save": "저장",
    "exit": "종료",
    "reset": "재설정",
    "choose_replacements": "대체 변수 선택",
    "new-goal": "새로운 목표",
    "about": "정보",
    "help": "도움",
    "undo": "실행 취소",
    "redo": "실행 다시",
    "settings": "설정",
    "load": "로드",
  },
  nl: {
    "add": "Toevoegen",
    "cancel": "Annuleren",
    "apply": "Toepassen",
    "save": "Opslaan",
    "exit": "Afsluiten",
    "reset": "Reset",
    "choose_replacements": "Kies vervangingen",
    "new-goal": "Nieuw doel",
    "about": "Over",
    "help": "Help",
    "undo": "Ongedaan maken",
    "redo": "Opnieuw",
    "settings": "Instellingen",
    "load": "Laden",
  },
  pt: {
    "add": "Adicionar",
    "cancel": "Cancelar",
    "apply": "Aplicar",
    "save": "Salvar",
    "exit": "Sair",
    "reset": "Resetar",
    "choose_replacements": "Escolha substituições",
    "new-goal": "Novo objetivo",
    "about": "Sobre",
    "help": "Ajuda",
    "undo": "Desfazer",
    "redo": "Refazer",
    "settings": "Configurações",
    "load": "Carregar",
  },
  zh: {
    "add": "添加",
    "cancel": "取消",
    "apply": "应用",
    "save": "保存",
    "exit": "退出",
    "reset": "重置",
    "choose_replacements": "选择替换",
    "new-goal": "新目标",
    "about": "关于",
    "help": "帮助",
    "undo": "撤销",
    "redo": "重做",
    "settings": "设置",
    "load": "加载",
  },
  uk: {
    "add": "Додати",
    "cancel": "Скасувати",
    "apply": "Застосувати",
    "save": "Зберегти",
    "exit": "Вийти",
    "reset": "Скинути",
    "choose_replacements": "Виберіть заміни",
    "new-goal": "Нова мета",
    "about": "Про",
    "help": "Допомога",
    "undo": "Скасувати",
    "redo": "Повторити",
    "settings": "Налаштування",
    "load": "Завантажити",
  },
};

export function _(key, lang) {
  var selected_lang = lang || window.navigator.userLanguage || window.navigator.language || "en";
  const lang_only = selected_lang.split("-")[0];
  if (lang_only in translations) {
    if (key in translations[lang_only]) {
      return translations[lang_only][key];
    }
  }
  if (key in translations["en"]) {
    return translations["en"][key];
  }
  return key;
}